version: '3.8'

services:
  jenkins:
    build: .
    container_name: jenkins
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - ${HOME}/.docker/desktop/docker.sock:/var/run/docker.sock
      - ${HOME}/jenkins-kube:/root/.kube:ro
      - ${HOME}/.minikube:/home/chiragvaze/.minikube:ro
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    restart: unless-stopped

volumes:
  jenkins_home:
